version: "3"

services:

  elasticsearch:
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    image: elasticsearch:5
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health | egrep 'yellow|green'
      interval: 30s
      retries: 3
  kibana:
    image: kibana:5.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elk
    deploy:
      mode: replicated
    healthcheck:
      test: wget -qO- http://localhost:5601 > /dev/null
      interval: 30s
      retries: 3
  logstash:
    command: sh -c "logstash -e 'input { syslog  { type => syslog port => 10514   } gelf { } beats { port => 5044 } } output { stdout { codec => rubydebug } elasticsearch { hosts => [ \"elasticsearch\" ] } }'"
    image: logstash:5.2-alpine
    ports:
      - "10514:10514/tcp"
      - "10514:10514/udp"
      - "12201:12201/udp"
      - "5044:5044/tcp"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

volumes:
  esdata:
    driver: local

networks:
  elk:

